# Generated by Django 3.1.6 on 2021-02-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_thoughts_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thoughts',
            name='pub_date',
        ),
    ]
